<?php if($this->getConfig('enabled') == 1):?>
	<?php
		$auto = $this->getConfig('auto');
		$itemsDefault = $this->getConfig('itemsDefault');
		$itemsDesktop = $this->getConfig('itemsDesktop');
		$itemsDesktopSmall = $this->getConfig('itemsDesktopSmall');
		$itemsTablet = $this->getConfig('itemsTablet');
		$itemsMobile = $this->getConfig('itemsMobile');
		$speed = $this->getConfig('speed');
		$next_back = $this->getConfig('next_back');
		$nav_ctrl = $this->getConfig('nav_ctrl');
		$rows = $this->getConfig('row_show');
		$i = 0;
	?>
	<div class="block block-testimonial-sidebar">	
		<div class="testimonial-content">
		<?php $latestTestimonial = $this->getTestimonialsLast()?>
		<?php if(count($latestTestimonial) > 0):?>
			<div class="ma-title testimonial-title">
				<h2><?php echo $this->__('Testimonials')?></h2>
			</div>
			<div class="block-content">
				<ul class="owl">			
					<?php foreach($latestTestimonial as $_item):?>
						<?php if($i % $rows == 0) echo "<li class='testimonial-list'>"; ?>		

							<?php 
								$testimonial_content = "f-col f-col-1 col-sm-6 col-md-8 col-sms-6 col-smb-12";
								if($_item->getAvatar() != ''){
									$avatarLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .$_item->getAvatar();
								}

								if(empty($avatarLink)) {
									$testimonial_content = "f-col f-col-1 col-sm-12 col-md-12 col-sms-12 col-smb-12";
								}
							?>						
							<div class="testimonial-sidebar-content">
								<div class="avata-post">
									<?php if(!empty($avatarLink)) { ?>
									<div class="testimonial-content-avatar f-col f-col-1 col-sm-6 col-md-4 col-sms-6 col-smb-12">
										<img src="<?php echo $avatarLink ?>" alt="test" />
									</div>
									<?php } ?>		
								</div>
								<div class="content <?php echo $testimonial_content ?>">	
									<i class="fa fa-quote-left"></i>&emsp;
									<a class="test-des" href="<?php echo $this->getUrl('testimonial')?>">						    
									<?php									
										$_description = $_item->getTestimonial();									
										$short_desc = $this->getContentTestimonialSidebar($_description, 300);									
										echo $short_desc;							    ?>						   
									</a>
									&emsp;<i class="fa fa-quote-right"></i>
									<hr/>
									<div class="post-by">							
										<span class="testimonial-author"><?php echo $_item->getName(); ?></span>							
										<span class="testimonial-date"><?php echo date('F d, Y', Mage::getModel('core/date')->gmtTimestamp($_item->getCreatedTime())); ?></span>						
									</div>	
									
								</div>		
								
							</div>
							<?php $i++;?>
						<?php if($i %$rows == 0) echo "</li>"; ?>                    
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</li>"; ?>		
				</ul>
			</div>	
		<?php endif ?>	
	</div>
	</div>
	<script type="text/javascript">
		$jq(document).ready(function(){
			$jq(".block-testimonial-sidebar .owl").owlCarousel({
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				items : <?php if($itemsDefault) echo $itemsDefault; else echo '5'; ?>,
				itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
				itemsDesktopSmall : [980,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
				itemsTablet: [768,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
				itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
				stopOnHover : true,
				pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
				scrollPerPage:true,
			});
		});
	</script>
<?php endif ?>