<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
	var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
</script>
<div class="wrap" id="sk_wrap">
	<div class="container" id="sk_container">
		<img id="sk_canvas_img"  class="sk_canvas_img"  style="position:absolute;top:0;right:0;margin-top:-10px" ></img> 
		<img id="sk_canvas_img1"  class="sk_canvas_img"    style="position:absolute;top:0;right:0;margin-top:-10px" ></img> 
		<img id="sk_canvas_img2"  class="sk_canvas_img"    style="position:absolute;top:0;right:0;margin-top:-10px" ></img> 
		<img id="sk_canvas_img3"  class="sk_canvas_img"    style="position:absolute;top:0;right:0;margin-top:-10px" ></img> 
		<img id="sk_canvas_img4"  class="sk_canvas_img"    style="position:absolute;top:0;right:0;margin-top:-10px" ></img> 
		<img id="sk_canvas_imgs2"   class="sk_canvas_img"    style="position:absolute;top:0;right:0;margin-top:-10px" ></img> 
		<div class="sk_pull_back" id="div_sk_text" style=""    ></div>
		<div class="sk_pull_back"   id="div_sk_text_1" style=""    ></div>
		<canvas id="sk_canvas_text_sample"   class="sk_canvas_text"  ></canvas>
		<canvas id="sk_canvas_text"       class="sk_canvas_text"     ></canvas>
		<canvas id="sk_canvas_text1" class="sk_canvas_text"  ></canvas>
		<canvas id="sk_canvas_text2" class="sk_canvas_text" ></canvas>
		<canvas id="sk_canvas_text3" class="sk_canvas_text"  ></canvas>
		<canvas id="sk_canvas_text4" class="sk_canvas_text"  ></canvas>
		<canvas id="sk_canvas_s2"  class="sk_canvas_text"   ></canvas>
		<div class="row" id="sk_main_row">
			<div class="col-md-7 sk_mb_40 " id="sk_design_tool_box" style="z-index: 9999;   ">
				<div class="row">
					<div class="col-md-12 sk_menu_bar" >
						<div class="logo sk_logo">
							<img src="<?php echo $this->getSkinUrl('images/basketball.png') ?>" alt="Basketball" />
						</div>
						<div class="basketball sk_basketball">
							<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
						</div>
						<?php if($_product->isSaleable()): ?>
						
							<form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
							<?php 
								$optionsBlock = Mage::app()->getLayout()->createBlock('catalog/product_view_options'); 
								$optionsBlock->addOptionRenderer('file', 'catalog/product_view_options_type_file', 'catalog/product/view/options/type/file.phtml')
							?>
							<?php $_options = Mage::helper('core')->decorateArray($optionsBlock->getOptions()) ?>
							<?php if (count($_options)):?>
								<script type="text/javascript">
								//<![CDATA[
								var optionFileUpload = {
									productForm : $p('product_addtocart_form'),
									formAction : '',
									formElements : {},
									upload : function(element){
										this.formElements = this.productForm.select('input', 'select', 'textarea', 'button');
										this.removeRequire(element.readAttribute('id').sub('option_', ''));

										template = '<iframe id="upload_target" name="upload_target" style="width:0; height:0; border:0;"><\/iframe>';

										Element.insert($p('option_'+element.readAttribute('id').sub('option_', '')+'_uploaded_file'), {after: template});

										this.formAction = this.productForm.action;

										var baseUrl = '<?php echo $optionsBlock->getUrl('*/product/upload') ?>';
										var urlExt = 'option_id/'+element.readAttribute('id').sub('option_', '');

										this.productForm.action = parseSidUrl(baseUrl, urlExt);
										this.productForm.target = 'upload_target';
										this.productForm.submit();
										this.productForm.target = '';
										this.productForm.action = this.formAction;
									},
									removeRequire : function(skipElementId){
										for(var i=0; i<this.formElements.length; i++){
											if (this.formElements[i].readAttribute('id') != 'option_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
												this.formElements[i].disabled='disabled';
											}
										}
									},
									addRequire : function(skipElementId){
										for(var i=0; i<this.formElements.length; i++){
											if (this.formElements[i].readAttribute('name') != 'options_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
												this.formElements[i].disabled='';
											}
										}
									},
									uploadCallback : function(data){
										this.addRequire(data.optionId);
										$p('upload_target').remove();

										if (data.error) {

										} else {
											$p('option_'+data.optionId+'_uploaded_file').value = data.fileName;
											$p('option_'+data.optionId+'_file').value = '';
											$p('option_'+data.optionId+'_file').hide();
											$p('option_'+data.optionId+'').hide();
											template = '<div id="option_'+data.optionId+'_file_box"><a href="#"><img src="var/options/'+data.fileName+'" alt=""><\/a><a href="#" onclick="optionFileUpload.removeFile('+data.optionId+')" title="Remove file" \/>Remove file<\/a>';

											Element.insert($p('option_'+data.optionId+'_uploaded_file'), {after: template});
										}
									},
									removeFile : function(optionId)
									{
										$p('option_'+optionId+'_uploaded_file').value= '';
										$p('option_'+optionId+'_file').show();
										$p('option_'+optionId+'').show();

										$p('option_'+optionId+'_file_box').remove();
									}
								}
								var optionTextCounter = {
									count : function(field,cntfield,maxlimit){
										if (field.value.length > maxlimit){
											field.value = field.value.substring(0, maxlimit);
										} else {
											cntfield.innerHTML = maxlimit - field.value.length;
										}
									}
								}

								Product.Options = Class.create();
								Product.Options.prototype = {
									initialize : function(config) {
										this.config = config;
										this.reloadPrice();
										document.observe("dom:loaded", this.reloadPrice.bind(this));
									},
									reloadPrice : function() {
										var config = this.config;
										var skipIds = [];
										$$('body .product-custom-option').each(function(element){
											var optionId = 0;
											element.name.sub(/[0-9]+/, function(match){
												optionId = parseInt(match[0], 10);
											});
											if (config[optionId]) {
												var configOptions = config[optionId];
												var curConfig = {price: 0};
												if (element.type == 'checkbox' || element.type == 'radio') {
													if (element.checked) {
														if (typeof configOptions[element.getValue()] != 'undefined') {
															curConfig = configOptions[element.getValue()];
														}
													}
												} else if(element.hasClassName('datetime-picker') && !skipIds.include(optionId)) {
													dateSelected = true;
													$$('.product-custom-option[id^="options_' + optionId + '"]').each(function(dt){
														if (dt.getValue() == '') {
															dateSelected = false;
														}
													});
													if (dateSelected) {
														curConfig = configOptions;
														skipIds[optionId] = optionId;
													}
												} else if(element.type == 'select-one' || element.type == 'select-multiple') {
													if ('options' in element) {
														$A(element.options).each(function(selectOption){
															if ('selected' in selectOption && selectOption.selected) {
																if (typeof(configOptions[selectOption.value]) != 'undefined') {
																	curConfig = configOptions[selectOption.value];
																}
															}
														});
													}
												} else {
													if (element.getValue().strip() != '') {
														curConfig = configOptions;
													}
												}
												if(element.type == 'select-multiple' && ('options' in element)) {
													$A(element.options).each(function(selectOption) {
														if (('selected' in selectOption) && typeof(configOptions[selectOption.value]) != 'undefined') {
															if (selectOption.selected) {
																curConfig = configOptions[selectOption.value];
															} else {
																curConfig = {price: 0};
															}
															optionsPrice.addCustomPrices(optionId + '-' + selectOption.value, curConfig);
															optionsPrice.reload();
														}
													});
												} else {
													optionsPrice.addCustomPrices(element.id || optionId, curConfig);
													optionsPrice.reload();
												}
											}
										});
									}
								}
								function validateOptionsCallback(elmId, result) {
									var container = $p(elmId).up('.options-list');
									if (result == 'failed') {
										container.removeClassName('validation-passed');
										container.addClassName('validation-failed');
									} else {
										container.removeClassName('validation-failed');
										container.addClassName('validation-passed');
									}
								}
								var opConfig = new Product.Options(<?php echo $optionsBlock->getJsonConfig() ?>);
								//]]>
								</script>
								<div class="options-list">
								<?php 
									$_defaultValues = array(
										'Body Color' => 'NAVY',
										'Collar Color' => 'VEGAS',
										'Primary' => 'LIME',
										'Secondary' => 'SILVER',
										'Tertiary' => 'LIME',
										'Team Name' => 'HAWKS',
										'Team Name Position' => 'Full Front',
										'Team Name Color' => 'LIME',
										'Team Name Font' => 'Varsity',
										'Team Name Border' => 'Black',
										'Team Name Layout' => 'Straight',
										'Number' => '34',
										'Number Position' => 'Full Back',
										'Number Color' => 'LIME',
										'Number Font' => 'Varsity',
										'Number Border' => 'SILVER'
									);
								?>
								<?php foreach ($_options as $_option): ?>
									<?php if(strtolower($_option->getType())=='file'): ?>
										<div class="div_sk_style_label input-file-container <?php echo Mage::getModel('catalog/product_url')->formatUrlKey('option-'.$_option->getTitle()) ?>">
										<?php echo $optionsBlock->getOptionHtml($_option) ?>
										</div>
									<?php elseif($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_AREA): ?>
									<textarea onchange="opConfig.reloadPrice()" id="options_<?php echo $_option->getId() ?>_text" class="div_sk_style_label input-text <?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> <?php echo $_option->getMaxCharacters() ? ' validate-length maximum-length-'.$_option->getMaxCharacters() : '' ?> product-custom-option <?php echo Mage::getModel('catalog/product_url')->formatUrlKey('option-'.$_option->getTitle()) ?>" name="options[<?php echo $_option->getId() ?>]"><?php echo $this->escapeHtml($this->getDefaultValue()) ?></textarea>
									<?php else: ?>
									<input type="text" onchange="opConfig.reloadPrice()" id="options_<?php echo $_option->getId() ?>_text" class="div_sk_style_label input-text<?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> <?php echo $_option->getMaxCharacters() ? ' validate-length maximum-length-'.$_option->getMaxCharacters() : '' ?> product-custom-option <?php echo Mage::getModel('catalog/product_url')->formatUrlKey('option-'.$_option->getTitle()) ?>" name="options[<?php echo $_option->getId() ?>]" value="<?php echo $this->escapeHtml(isset($_defaultValues[$_option->getTitle()])?$_defaultValues[$_option->getTitle()]:$this->getDefaultValue()) ?>" />
									<?php endif ?>
								<?php endforeach ?>
								</div>
							
							<?php endif ?>
			
								<div class="buynow sk_buynow" >
									<div style="display:none;">QTY: <input type="number" name="qty" id="qty" value="8" style="width: 50px;line-height: 30px;text-align: center;color: #000;" maxlength="12" /></div> 
									<a class="btn-default btn-lg " href="#" onclick="productAddToCartForm.submit();return false;">Buy Now</a> @ <span class="price" id="spn_price">
									<?php echo $this->getPriceHtml($_product) ?></span> only
								</div>
								
															
							</form>
			
						<?php endif;?>
						<a href="javascript:void(0)" id="btn_close">
						<img src="<?php echo $this->getSkinUrl('images/close.png') ?>" alt="Close">
						</a>
					</div>
				</div>
				<div class="sk_mb_40"  >
					<div style="font-size:22px;color:fff;display:none">
						<p style="font-family:tiffany;">tiffany</p>
						<p style="font-family:speed;">speed</p>
						<p style="font-family:scriptjet;">scriptjet</p>
						<p style="font-family:varsity;">varsity</p>
						<p style="font-family:sk_bold;">bold</p>
						<p style="font-family:nitro;">nitro</p>
						<p style="font-family:slab;">slab</p>
						<p style="font-family:;blast">blast</p>
						<p style="font-family:impact;">impact</p>
						<p style="font-family:saw;">saw</p>
						<p style="font-family:cooper;">cooper</p>
						<p style="font-family:narrow;">narrow</p>
						<p style="font-family:arizona;">arizona</p>
						<p style="font-family:express;">express</p>
					</div>
					<div id="div_sk_panel_main" class="sk_line_scroll">
						<div class="row">
							<div class="col-md-12">
								<h1  >
									Select Garment
								</h1>
								<div class="row sk_div_row"  >
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4  col-xs-4">
										<a class="a_sk_action" data-val="style" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/check.png') ?>" alt="Check" />
										</span>
										<span class="icon">
										<img src="<?php echo $this->getSkinUrl('images/style.png') ?>" class="sk_icon_img" alt="Style" />
										</span>
										<span class="lable sk_label">Style</span>
										</a>
									</div>
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4">
										<a class="a_sk_action" data-val="fabric" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/check.png') ?>" alt="Check" />
										</span>
										<span class="icon">
										<img src="<?php echo $this->getSkinUrl('images/fabric.png') ?>" class="sk_icon_img" alt="Fabric" />
										</span>
										<span class="lable sk_label">Fabric</span>
										</a>
									</div>
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4">
										<a class="a_sk_action" data-val="colors" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/add.png') ?>" alt="Add" />
										</span>
										<span class="icon">
										<img src="<?php echo $this->getSkinUrl('images/color.png') ?>" class="sk_icon_img" alt="Color" />
										</span>
										<span class="lable sk_label">Colors</span>
										</a>
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<h1>
									Name &amp; Number
								</h1>
								<div class="row sk_div_row"  >
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4">
										<a class="a_sk_action" data-val="team_name" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/add.png') ?>"   alt="Add" />
										</span>
										<span class="icon sk_icon">
										<img src="<?php echo $this->getSkinUrl('images/team.png') ?>" class="sk_icon_img" alt="Team Name" />
										</span>
										<span class="lable sk_label">Team Name </span>
										</a>
									</div>
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4">
										<a class="a_sk_action" data-val="player_name" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/add.png') ?>" alt="Add" />
										</span>
										<span class="icon">
										<img src="<?php echo $this->getSkinUrl('images/player.png') ?>" class="sk_icon_img" alt="Player Name" />
										</span>
										<span class="lable sk_label">Player Name</span>
										</a>
									</div>
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4">
										<a class="a_sk_action" data-val="number" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/add.png') ?>" alt="Add" />
										</span>
										<span class="icon">
										<img src="<?php echo $this->getSkinUrl('images/number.png') ?>" class="sk_icon_img" alt="Number" />
										</span>
										<span class="lable sk_label">Number</span>
										</a>
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<h1>
									Select Logo
								</h1>
								<div class="row sk_div_row"  >
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4">
										<a class="a_sk_action" data-val="front_logo" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/add.png') ?>" alt="Add" />
										</span>
										<span class="icon">
										<img src="<?php echo $this->getSkinUrl('images/front_logo.png') ?>" class="sk_icon_img" alt="Front Logo" />
										</span>
										<span class="lable sk_label">Front Logo</span>
										</a>
									</div>
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4">
										<a class="a_sk_action" data-val="shorts_mascot" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/add.png') ?>" alt="Add" />
										</span> 
										<span class="icon sk_icon">
										<img src="<?php echo $this->getSkinUrl('images/shorts.png') ?>" class="sk_icon_img" alt="Left Sleeve Logo" />
										</span>
										<span class="lable sk_label">Shorts Mascot</span>
										</a>
									</div>
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4">
										<a class="a_sk_action" data-val="back_logo" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/add.png') ?>" alt="Add" />
										</span>
										<span class="icon">
										<img src="<?php echo $this->getSkinUrl('images/back_logo.png') ?>" class="sk_icon_img"  alt="Back Logo" />
										</span>
										<span class="lable sk_label">Back Logo</span>
										</a>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<h1>
									Roster &amp; Instructions
								</h1>
								<div class="row sk_div_row"  >
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4 roster-section">
										<a class="a_sk_action" data-val="roster" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/add.png') ?>" alt="Add" />
										</span>
										<span class="icon sk_icon">
										<img src="<?php echo $this->getSkinUrl('images/roster.png') ?>" class="sk_icon_img" alt="Roster" />
										</span>
										<span class="lable sk_label">Roster</span>
										</a>
									</div>
									<div class="icon_row sk_icon_row col-md-4  col-sm-4  col-lg-4   col-xs-4 instructions-section">
										<a class="a_sk_action" data-val="instruction" >
										<span class="sign">
										<img src="<?php echo $this->getSkinUrl('images/add.png') ?>" alt="Add" />
										</span>
										<span class="icon sk_icon">
										<img src="<?php echo $this->getSkinUrl('images/instructions.png') ?>" class="sk_icon_img" alt="Instructions" />
										</span>
										<span class="lable sk_label">Instructions</span>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_style" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/style.png') ?>" alt="Styles" />
								</div>
								<h2 class="inner-heading">Styles</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="col-md-4">
										<div class="jersey div_sk_style_label_img">
											<div class="style_check">
												<img src="<?php echo $this->getSkinUrl('images/check.png') ?>" alt="selected" />
											</div>
											<img src="<?php echo $this->getSkinUrl('images/fabric6.png') ?>" alt="fabric" />
											<p class="sk_model_name">
												578 | Swoosh Full Dye Sublimated Basketball Set
											</p>
										</div>
										<div class="style-lable_active  div_sk_style_label" data-val="S1">
											<a href="javascript:void(0)"> Pin Hole</a>
										</div>
									</div>
									<div class="col-md-4">
										<div class="jersey div_sk_style_label_img">
											<img src="<?php echo $this->getSkinUrl('images/fabric1.png') ?>" alt="fabric" />
											<p class="sk_model_name">
												576 | Fadeaway Full Dye Sublimated Basketball Set
											</p>
										</div>
										<div class="style-lable div_sk_style_label" data-val="S2">
											<a href="javascript:void(0)">Pro Aero	</a>
										</div>
									</div>
									<div class="col-md-4">
										<div class="jersey div_sk_style_label_img">
											<img src="<?php echo $this->getSkinUrl('images/fabric3.png') ?>" alt="fabric" />
											<p class="sk_model_name">
												579 | Phoenix Full Dye Sublimated Basketball Set
											</p>
										</div>
										<div class="style-lable div_sk_style_label" data-val="S5">
											<a href="javascript:void(0)">  Stretch</a>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="col-md-4">
										<div class="jersey div_sk_style_label_img">
											<img src="<?php echo $this->getSkinUrl('images/fabric5.png') ?>" alt="fabric" />
											<p class="sk_model_name">
												577 | All Star Full Dye Sublimated Basketball Set
											</p>
										</div>
										<div class="style-lable div_sk_style_label" data-val="S3">
											<a href="javascript:void(0)">  Pro Aero</a>
										</div>
									</div>
									<div class="col-md-4">
										<div class="jersey div_sk_style_label_img">
											<img src="<?php echo $this->getSkinUrl('images/fabric2.png') ?>" alt="fabric" />
											<p class="sk_model_name">
												580 | Caliber Full Dye Sublimated Basketball Set
											</p>
										</div>
										<div class="style-lable div_sk_style_label" data-val="S6">
											<a href="javascript:void(0)">  Stretch</a>
										</div>
									</div>
									<div class="col-md-4">
										<div class="jersey div_sk_style_label_img">
											<img src="<?php echo $this->getSkinUrl('images/fabric4.png') ?>" alt="fabric" />
											<p class="sk_model_name">
												575 | Superior Full Dye Sublimated Basketball Set
											</p>
										</div>
										<div class="style-lable div_sk_style_label" data-val="S4">
											<a href="javascript:void(0)">Bunker Grid</a>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="col-md-4">
										<div class="jersey div_sk_style_label_img">
											<img src="<?php echo $this->getSkinUrl('images/fabric7.png') ?>" alt="fabric" />
											<p class="sk_model_name">
												573 | Enforcer Full Dye Sublimated Basketball Set
											</p>
										</div>
										<div class="style-lable div_sk_style_label" data-val="S7">
											<a href="javascript:void(0)">  Pro Aero</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_fabric" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/fabric.png') ?>" alt="Fabric" />
								</div>
								<h2 class="inner-heading">Fabric</h2>
							</div>
							<div class="col-md-12 sk_line_scroll"  >
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
										<div class="jersey div_sk_fabric_label_img">
											<div class="style_check">
												<img src="<?php echo $this->getSkinUrl('images/check.png') ?>" alt="selected" />
											</div>
											<img src="<?php echo $this->getSkinUrl('images/dri-feel.jpg') ?>" alt="fabric" />
										</div>
										<div class="style-lable_active div_sk_fabric_label" data-val="dri_feel">
											<a href="javascript:void(0)">Dri Feel</a>
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
										<div class="jersey div_sk_fabric_label_img"> 
											<img src="<?php echo $this->getSkinUrl('images/micro-fiber.jpg') ?>" alt="fabric" />
										</div>
										<div class="style-lable div_sk_fabric_label" data-val="micro_fiber">
											<a href="javascript:void(0)">  Micro Fiber</a>
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
										<div class="jersey div_sk_fabric_label_img"> 
											<img src="<?php echo $this->getSkinUrl('images/micro-pique.jpg') ?>" alt="fabric" />
										</div>
										<div class="style-lable div_sk_fabric_label" data-val="micro_pique">
											<a href="javascript:void(0)">Micro Pique</a>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
										<div class="jersey div_sk_fabric_label_img"> 
											<img src="<?php echo $this->getSkinUrl('images/pro-comfort.jpg') ?>" alt="fabric" />
										</div>
										<div class="style-lable  div_sk_fabric_label" data-val="pro_comfort">
											<a href="javascript:void(0)"> Pro Comfort</a>
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
										<div class="jersey div_sk_fabric_label_img"> 
											<img src="<?php echo $this->getSkinUrl('images/pro-flexx.jpg') ?>" alt="fabric" />
										</div>
										<div class="style-lable div_sk_fabric_label" data-val="pro_flexx">
											<a href="javascript:void(0)">Pro Flexx	</a>
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
										<div class="jersey div_sk_fabric_label_img"> 
											<img src="<?php echo $this->getSkinUrl('images/sportknit.jpg') ?>" alt="fabric" />
										</div>
										<div class="style-lable div_sk_fabric_label" data-val="sportknit">
											<a href="javascript:void(0)">  Sportknit</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_colors" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/color.png') ?>" alt="Colors" />
								</div>
								<h2 class="inner-heading">Colors</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn_sk_color_label" data-val="body_color">
											<span class="btn-label" >
											<i class="fa fa-eyedropper"></i>
											</span>Body Color</button>
										</div>
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn_sk_color_label" data-val="collar_color" >
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Collar Color</button>
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn_sk_color_label" data-val="primary" >
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Design Color - Primary</button>
										</div>
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn_sk_color_label" data-val="secondary" >
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Design Color - Secondary</button>
										</div>
										<div class="button-hold" style=" ">
											<button type="button" class="btn btn-labeled btn-default btn_sk_color_label" data-val="tertiary" >
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Design Color - Tertiary</button>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_team_name" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/team.png') ?>" alt="Team Name" />
								</div>
								<h2 class="inner-heading">Team Name</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_tname" value="" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>None</label>
										</div>
									</div>
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_tname" value="full_front" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>Full Front</label>
										</div>
									</div>
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_tname" value="left_chest" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>Left Chest
											</label>
										</div>
									</div>
								</div>
								<div class="info">
									<em>Team Name is potentially overlapping with Front Logo – only one of them can be placed at a specific placement.</em>
								</div>
								<div class="team_name">
									<input type="text" class="form-control" id="txt_team_name"  name="txt_team_name" placeholder="Enter Team Name Here" />
									<div class="info">
										<em>Only letters, numbers and spaces are allowed.</em>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_team_name_label"  data-val="team_name_color">
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Color</button>
										</div>
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_team_name_label" data-val="team_name_border" >
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Out Line Color 1</button>
										</div>
									</div>
									<div class="col-md-6">
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_font_label" data-val="team_name">
											<span class="btn-label" data-val="">
											<i class="fa fa-font" aria-hidden="true"></i>
											</span>Font</button>
										</div>
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width  btn_sk_layout_label" data-val="team_name"  >
											<span class="btn-label" data-val="">
											<i class="fa fa-object-ungroup" aria-hidden="true"></i>
											</span>layout</button>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_player_name" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/player.png') ?>" alt="Player Name" />
								</div>
								<h2 class="inner-heading">Player Name</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_pname" value="" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>None</label>
										</div>
									</div>
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_pname" value="upper_back" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>Upper Back</label>
										</div>
									</div>
								</div>
								<p class="info"><em>Custom Player Name Charges - $4.00</em></p>
								<div class="info"><em>Player Name is potentially overlapping with Back Logo - only one of them can be placed at a specific placement.</em></div>
								<div class="team_name">
									<input type="text" class="form-control" id="txt_player_name"  name="txt_player_name" placeholder="Enter Player Name Here" />
									<div class="info">
										<em>Only letters, numbers and spaces are allowed.</em>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_player_name_label" data-val="player_name_color">
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Color</button>
										</div>
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_player_name_label"  data-val="player_name_border">
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Out Line Color 1</button>
										</div>
									</div>
									<div class="col-md-6">
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_font_label" data-val="player_name">
											<span class="btn-label" data-val="">
											<i class="fa fa-font" aria-hidden="true"></i>
											</span>Font</button>
										</div>
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width  btn_sk_layout_label" data-val="player_name"  >
											<span class="btn-label" data-val="">
											<i class="fa fa-object-ungroup" aria-hidden="true"></i>
											</span>layout</button>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_number" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/number.png') ?>" alt="Number" />
								</div>
								<h2 class="inner-heading">Number</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_number" value="" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>None</label>
										</div>
									</div>
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_number" value="under" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>Under</label>
										</div>
									</div>
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_number" value="heart" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>Heart</label>
										</div>
									</div>
								</div>
								<div class="team_name">
									<input type="text" class="form-control" onfocus="this.type='number'" id="txt_number"  maxlength="3" name="txt_number" placeholder="Enter Player Name Here" />
								</div>
								<div class="row">
									<div class="col-md-6">
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_number_label"  data-val="number_color">
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Color</button>
										</div>
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_number_label"  data-val="number_border">
											<span class="btn-label" data-val="">
											<i class="fa fa-eyedropper"></i>
											</span>Out Line Color 1</button>
										</div>
									</div>
									<div class="col-md-6">
										<div class="button-hold">
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_font_label" data-val="number">
											<span class="btn-label" data-val="">
											<i class="fa fa-font" aria-hidden="true"></i>
											</span>Font</button>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_front_logo" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/front_logo.png') ?>" alt="Front Logo" />
								</div>
								<h2 class="inner-heading">Front Logo</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_front_logo" value="" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>None</label>
										</div>
									</div>
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_front_logo" value="full_front" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>Full Front</label>
										</div>
									</div>
								</div>
								<div class="info">
									<em>Front Logo is potentially overlapping with Team Name - only one of them can be placed at a specific placement.</em>
								</div>
								<div class="row">
									<div class="col-md-6">
										<h3>Select stock logo</h3>
										<p>
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_logo_label" data-val="front_logo"  >
											<span class="btn-label" >
											<i class="fa fa-circle" aria-hidden="true"></i>
											</span>Stock Logos</button>
										</p>
										<p class="info">
											<em>To enable preview please upload a raster image - jpeg, gif or png with transparency. We can not display Illustrator, Photoshop, CorelDraw, PDF and other production files.</em>
										</p>
										<div class="mascots-selected" >
											<img id="img_preview_front_logo"  class="img_preview_sk_logo"  src="" alt="font" />
										</div>
									</div>
									<div class="col-md-6">
										<h3>Upload custom logo </h3>
										<div class="input-group image-preview">
											<input type="text" class="form-control image-preview-filename" disabled="disabled" /> 
											<span class="input-group-btn">
											<button type="button" class="btn btn-default image-preview-clear" style="display:none;">
												<span class="glyphicon glyphicon-remove"/>
													Clear
											</button>
											<div class="btn btn-default image-preview-input">
											<span class="glyphicon glyphicon-folder-open"></span>
											<span class="image-preview-input-title">Browse</span>
											<input type="file" accept="image/png, image/jpeg, image/gif" data-val="front_logo" name="file_front_logo" id="file_front_logo"/>
											</div>
											</span>
										</div>
										<br clear="all"/>
										<p class="info">
											<em>Custom logo Charges - $8.00</em>
										</p>
										<div class="info">
											<em>To streamline the inquiry and production process please provide high resolution vector files - eps, ai or pdf files.</em>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_shorts_mascot" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/shorts.png') ?>" alt="Shorts Mascot" />
								</div>
								<h2 class="inner-heading">Shorts Mascot</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_shorts_mascot" value="" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>None</label>
										</div>
									</div>
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_shorts_mascot" value="full_front" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>Full Front</label>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<h3>Select stock logo</h3>
										<p>
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_logo_label" data-val="shorts_mascot"  >
											<span class="btn-label" >
											<i class="fa fa-circle" aria-hidden="true"></i>
											</span>Stock Logos</button>
										</p>
										<p class="info">
											<em>To enable preview please upload a raster image - jpeg, gif or png with transparency. We can not display Illustrator, Photoshop, CorelDraw, PDF and other production files.</em>
										</p>
										<div class="mascots-selected" >
											<img id="img_preview_shorts_mascot"  class="img_preview_sk_logo"  src="" alt="font" />
										</div>
									</div>
									<div class="col-md-6">
										<h3>Upload custom logo </h3>
										<div class="input-group image-preview">
											<input type="text" class="form-control image-preview-filename" disabled="disabled" /> 
											<span class="input-group-btn">
											<button type="button" class="btn btn-default image-preview-clear" style="display:none;">
												<span class="glyphicon glyphicon-remove"/>
													Clear
											</button>
											<div class="btn btn-default image-preview-input">
											<span class="glyphicon glyphicon-folder-open"></span>
											<span class="image-preview-input-title">Browse</span>
											<input type="file" accept="image/png, image/jpeg, image/gif" data-val="shorts_mascot" id="file_mascot_logo" name="file_mascot_logo"/>
											</div>
											</span>
										</div>
										<br clear="all"/>
										<p class="info">
											<em>Custom logo Charges - $2.00</em>
										</p>
										<div class="info">
											<em>To streamline the inquiry and production process please provide high resolution vector files - eps, ai or pdf files.</em>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_back_logo" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/back_logo.png') ?>" alt="Back Logo" />
								</div>
								<h2 class="inner-heading">Back Logo</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_back_logo" value="" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>None</label>
										</div>
									</div>
									<div class="col-md-4 ">
										<div class="radio">
											<label>
											<input type="radio" name="rdo_back_logo" value="upper_back" />
											<span class="cr">
											<i class="cr-icon fa fa-circle"></i>
											</span>Upper Back</label>
										</div>
									</div>
								</div>
								<div class="info">
									<em>Back Logo is potentially overlapping with Player Name - only one of them can be placed at a specific placement.</em>
								</div>
								<div class="row">
									<div class="col-md-6">
										<h3>Select stock logo</h3>
										<p>
											<button type="button" class="btn btn-labeled btn-default btn-width btn_sk_logo_label" data-val="back_logo"  >
											<span class="btn-label" >
											<i class="fa fa-circle" aria-hidden="true"></i>
											</span>Stock Logos</button>
										</p>
										<p class="info">
											<em>To enable preview please upload a raster image - jpeg, gif or png with transparency. We can not display Illustrator, Photoshop, CorelDraw, PDF and other production files.</em>
										</p>
										<div class="mascots-selected" >
											<img id="img_preview_back_logo" class="img_preview_sk_logo" src="" alt="font" />
										</div>
									</div>
									<div class="col-md-6">
										<h3>Upload custom logo </h3>
										<div class="input-group image-preview">
											<input type="text" class="form-control image-preview-filename" disabled="disabled" /> 
											<span class="input-group-btn">
											<button type="button" class="btn btn-default image-preview-clear" style="display:none;">
												<span class="glyphicon glyphicon-remove"/>
													Clear
											</button>
											<div class="btn btn-default image-preview-input">
											<span class="glyphicon glyphicon-folder-open"></span>
											<span class="image-preview-input-title">Browse</span>
											<input type="file" accept="image/png, image/jpeg, image/gif" data-val="back_logo" name="file_back_logo" id="file_back_logo"/>
											</div>
											</span>
										</div>
										<br clear="all"/>
										<p class="info">
											<em>Custom logo Charges - $8.00</em>
										</p>
										<div class="info">
											<em>To streamline the inquiry and production process please provide high resolution vector files - eps, ai or pdf files.</em>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_roster" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/roster.png') ?>" alt="Roster" />
								</div>
								<h2 class="inner-heading">Roster</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="space sk_space">
									</div>
									<table class="table">
										<thead>
											<tr>
												<th>Size</th>
												<th>Nr.</th>
												<th>Jersey Name</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<th scope="row">
													<select name="Size" class="form-control">
														<option>YS</option>
														<option>YM</option>
														<option>YL</option>
														<option>AXS</option>
														<option>AS</option>
														<option>AM</option>
														<option>AL</option>
														<option>AXL</option>
														<option>A2XL</option>
														<option>A3XL</option>
														<option>A4XL</option>
													</select>
												</th>
												<td>
													<input type="number" class="form-control" size="3" />
												</td>
												<td>
													<input name="" type="text" class="form-control" />
												</td>
											</tr>
										</tbody>
										<tfoot>
											<tr>
												<td scope="row" colspan="4">
													<button type="button" class="btn-default btn-lg btn-add-line">+ add line</button>
												</td>
											</tr>
										</tfoot>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_instruction" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/instructions.png') ?>" alt="Special Instructions" />
								</div>
								<h2 class="inner-heading">Special Instructions</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="space sk_space">
									</div>
									<textarea class="form-control" rows="5"></textarea>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_contact_me" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/contact.png') ?>" alt="Contact Me" />
								</div>
								<h2 class="inner-heading">Contact Me</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="form-area">
										<form action="<?php echo rtrim(Mage::getBaseUrl(),'/') ?>/contacts/index/post/" id="contactForm" method="post">
											<br style="clear:both"></br>
											<div class="form-group">
												<input type="text" class="form-control" id="name" name="name" placeholder="Name" required />
											</div>
											<div class="form-group">
												<input type="text" class="form-control" id="email" name="email" placeholder="Email" required  />
											</div>
											<div class="form-group">
												<input type="text" class="form-control" id="mobile" name="telephone" placeholder="Mobile Number" required />
											</div>
											<div class="form-group">
												<textarea class="form-control" type="textarea" id="message"
												placeholder="Message" name="comment"  maxlength="140" rows="7"></textarea>
											</div>
											<button type="submit" id="submit" name="submit" class="btn btn-primary pull-right">Submit Form</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_summary" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading"> 
								</div>
								<h2 class="inner-heading">Summary</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
											<div class="row summary">

								<div class="col-md-6">
									<div>
										<h4>Style</h4>
										<div id="summary-style" class="summary-details">
										</div>
									</div>
									<div>
										<h4>Fabric</h4>
										<div id="summary-fabric" class="summary-details">
										</div>
									</div>
									<div>
										<h4>Colors</h4>
										<div>
											<dl>
												<dt>Body:</dt>
												<dd id="summary-body-color" class="summary-details">NAVY</dd>
											</dl> 
											<dl>
												<dt>Colar:</dt>
												<dd  id="summary-collar-color" class="summary-details">VEGAS</dd>
											</dl>
											<dl>
												<dt>Primary:</dt>
												<dd  id="summary-primary-color" class="summary-details">LIME</dd>
											</dl>
											<dl>
												<dt>Secondary:</dt>
												<dd  id="summary-secondary-color" class="summary-details">SILVER</dd>
											</dl>
											<dl>
												<dt>Tertiary:</dt>
												<dd  id="summary-tertiary-color" class="summary-details">LIME</dd>
											</dl>
										</div>
									</div>
									<div>
										<h4>Team name</h4>
										<div>
											<dl>
												<dt>Position:</dt>
												<dd id="summary-team-name-position" class="summary-details">Full Front</dd>
											</dl>
											<dl>
												<dt>Text:</dt>
												<dd>
													<em id="summary-team-name" class="summary-details"></em>
												</dd>
											</dl>
											<dl>
												<dt>Color:</dt>
					<dd id="summary-team-name-color" class="summary-details">LIME</dd>						</dl>
											<div>
												<dl>
													<dt>Font:</dt>
													<dd id="summary-team-name-font" class="summary-details">Varsity</dd>
												</dl>
											</div>
											<dl>
												<dt>Outline color 1:</dt>
												<dd id="summary-team-name-border" class="summary-details">Black</dd>
											</dl> 
											<dl>
												<dt>Layout:</dt>
												<dd id="summary-team-name-layout" class="summary-details">Straight</dd>
											</dl>
										</div>
									</div>
								</div>

								<div class="col-md-6">
 
									<div>
										<h4>Number</h4>
										<div>
											<dl>
												<dt>Position:</dt>
												<dd id="summary-number-position" class="summary-details">Full Back</dd>
											</dl>
											<dl>
												<dt>Text:</dt>
												<dd>
													<em id="summary-number" class="summary-details">32</em>
												</dd>
											</dl>
											<dl>
												<dt>Font:</dt>
												<dd id="summary-number-font" class="summary-details">Varsity</dd>
											</dl>
											<dl>
												<dt>Color:</dt>
												<dd id="summary-number-color" class="summary-details">White</dd>
											</dl>
											<dl>
												<dt>Outline color:</dt>
												<dd id="summary-number-border" class="summary-details">Black</dd>
											</dl>
										</div>
									</div>
								</div>
								<hr>
								<p>Actual colors on product may vary.</p>
							</div>
										</div>
							<?php /*
							<div class="col-md-12 sk_line_scroll">
								<div class="row summary">
								<div class="col-md-12 sk_line_scroll">
								<?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getDescription(), 'description') ?>
								</div>
								</div>
									<hr />
									<p>Actual colors on product may vary.</p>
							</div> */ ?>
						</div>
					</div>
					</div>
					<div id="div_sk_panel_select_colors" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img src="<?php echo $this->getSkinUrl('images/color.png') ?>" alt="Select Colors" />
								</div>
								<h2 class="inner-heading">Select Color</h2>
							</div>
							<div class="col-md-12">
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="col-md-12 sk_line_scroll">
										<div class="color-pick">
											<ul>
												<li>
													<div class="div_sk_select_color_label" data-val="CARDINAL" style="background:#640d1b;"></div>
													CARDINAL
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="VEGAS" style="background:#8d855f;"></div>
													VEGAS
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="RUST-ORANGE" style="background:#8d3908;"></div>
													RUST ORANGE
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="WHITE" style="background:#f9f9f9;"></div>
													WHITE
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="MAROON" style="background:#331218;"></div>
													MAROON
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="ORANGE" style="background:#f45f31;"></div>
													ORANGE
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="YELLOW" style="background:#f9f880;"></div>
													YELLOW
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="FUCHSIA" style="background:#bb57a0;"></div>
													FUCHSIA
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="MINT" style="background:#47d1a5;"></div>
													MINT
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="LAVENDER" style="background:#8e8cef;"></div>
													LAVENDER
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="PINK" style="background:#e8b2fa;"></div>
													PINK
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="CYAN" style="background:#0377f9;"></div>
													CYAN
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="COLUMBIA" style="background:#7aabec;"></div>
													COLUMBIA
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="GRAPHITE" style="background:#3b4047;"></div>
													GRAPHITE
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="OPTIC" style="background:#8da62e;"></div>
													OPTIC
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="TEAL" style="background:#02776a;"></div>
													TEAL
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="LIME" style="background:#41bf44;"></div>
													LIME
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="PURPLE" style="background:#200d62;"></div>
													PURPLE
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="FOREST" style="background:#042d21;"></div>
													FOREST
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="SILVER" style="background:#6f7276;"></div>
													SILVER
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="NAVY" style="background:#0a1b33;"></div>
													NAVY
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="BLACK" style="background:#000000;"></div>
													BLACK
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="GOLD" style="background:#ffa508;"></div>
													GOLD
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="RED" style="background:#c20101;"></div>
													RED
												</li>
												<li>
													<div class="div_sk_select_color_label" data-val="ROYAL" style="background:#01347a;"></div>
													ROYAL
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_select_fonts" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img id="img_select_font" src="" alt="Select Fonts" />
								</div>
								<h2 class="inner-heading" id="headin_select_font"></h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="font-pick">
										<ul>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="tiffany">
													<img src="<?php echo $this->getSkinUrl('images/font1.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:tiffany;">tiffany</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="speed">
													<img src="<?php echo $this->getSkinUrl('images/font2.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:speed;">speed</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="scriptjet">
													<img src="<?php echo $this->getSkinUrl('images/font3.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:scriptjet;">scriptjet</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="varsity">
													<img src="<?php echo $this->getSkinUrl('images/font4.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:varsity;">varsity</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="sk_bold">
													<img src="<?php echo $this->getSkinUrl('images/font5.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:sk_bold;">bold</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="nitro">
													<img src="<?php echo $this->getSkinUrl('images/font6.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:nitro;">nitro</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="slab">
													<img src="<?php echo $this->getSkinUrl('images/font7.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:slab;">slab</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="blast">
													<img src="<?php echo $this->getSkinUrl('images/font8.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:;blast;font-style:italic;">blast</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="impact">
													<img src="<?php echo $this->getSkinUrl('images/font9.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:impact;">impact</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="saw">
													<img src="<?php echo $this->getSkinUrl('images/font10.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:saw;">saw</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="cooper">
													<img src="<?php echo $this->getSkinUrl('images/font11.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:cooper;">cooper</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="narrow">
													<img src="<?php echo $this->getSkinUrl('images/font12.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:narrow;">narrow</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="arizona">
													<img src="<?php echo $this->getSkinUrl('images/font13.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:arizona;font-style:italic;">arizona</p>
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_font_label" data-val="express">
													<img src="<?php echo $this->getSkinUrl('images/font14.png') ?>" alt="font" />
													<p class="sk_font_demo"  style="font-family:express;">express</p>
												</a>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_select_layout" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img id="img_select_layout" src="" alt="Select Layout" />
								</div>
								<h2 class="inner-heading" id="headin_select_layout"></h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="font-pick">
										<ul>
											<li><a href="javascript:void(0)" class="a_sk_select_layout_label" data-val="straight"><img src="<?php echo $this->getSkinUrl('images/layout1.png') ?>" alt="font" /></a></li>
											<li><a href="javascript:void(0)" class="a_sk_select_layout_label" data-val="rebookends"><img src="<?php echo $this->getSkinUrl('images/layout2.png') ?>" alt="font" /></a></li>
											<li><a href="javascript:void(0)" class="a_sk_select_layout_label" data-val="arch_lower"><img src="<?php echo $this->getSkinUrl('images/layout3.png') ?>" alt="font" /></a></li>
											<li><a href="javascript:void(0)" class="a_sk_select_layout_label" data-val="arch"><img src="<?php echo $this->getSkinUrl('images/layout4.png') ?>" alt="font" /></a></li>
											<li><a href="javascript:void(0)" class="a_sk_select_layout_label" data-val="slanted"><img src="<?php echo $this->getSkinUrl('images/layout5.png') ?>" alt="font" /></a></li>
											<li><a href="javascript:void(0)" class="a_sk_select_layout_label" data-val="bookends"><img src="<?php echo $this->getSkinUrl('images/layout6.png') ?>" alt="font" /></a></li>
											<li><a href="javascript:void(0)" class="a_sk_select_layout_label" data-val="arch_upper"><img src="<?php echo $this->getSkinUrl('images/layout7.png') ?>" alt="font" /></a></li>
											<li><a href="javascript:void(0)" class="a_sk_select_layout_label" data-val="italic"><img src="<?php echo $this->getSkinUrl('images/layout8.png') ?>" alt="font" /></a></li>
											<li><a href="javascript:void(0)" class="a_sk_select_layout_label" data-val="bowtie"><img src="<?php echo $this->getSkinUrl('images/layout9.png') ?>" alt="font" /></a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div_sk_panel_select_logo" class="sk_hide sk_other_box">
						<div class="row">
							<div class="space sk_space">
							</div>
							<div class="col-md-12 sk_line">
								<div class="back">
									<a class="a_sk_action" data-val="back">
									<img src="<?php echo $this->getSkinUrl('images/back_button.png') ?>" alt="Back" />
									<br/>Back</a>
								</div>
								<div class="icon-heading">
									<img id="img_select_logo" src="" alt="Select Layout" />
								</div>
								<h2 class="inner-heading" >Select Stock Logo</h2>
							</div>
							<div class="col-md-12 sk_line_scroll">
								<div class="row">
									<div class="space sk_space">
									</div>
									<div class="mascots-pick">
										<ul>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="1">
												<img src="<?php echo $this->getSkinUrl('images/mascots_1.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="2">
												<img src="<?php echo $this->getSkinUrl('images/mascots_2.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="3">
												<img src="<?php echo $this->getSkinUrl('images/mascots_3.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="4">
												<img src="<?php echo $this->getSkinUrl('images/mascots_4.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="5">
												<img src="<?php echo $this->getSkinUrl('images/mascots_5.jpg') ?>" alt="font" class="img_sk_select_logo"  />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="6">
												<img src="<?php echo $this->getSkinUrl('images/mascots_6.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="7">
												<img src="<?php echo $this->getSkinUrl('images/mascots_7.jpg') ?>" alt="font" class="img_sk_select_logo"  />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="8">
												<img src="<?php echo $this->getSkinUrl('images/mascots_8.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="9">
												<img src="<?php echo $this->getSkinUrl('images/mascots_9.jpg') ?>" alt="font" class="img_sk_select_logo"  />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="11">
												<img src="<?php echo $this->getSkinUrl('images/mascots_11.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="12">
												<img src="<?php echo $this->getSkinUrl('images/mascots_12.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="13">
												<img src="<?php echo $this->getSkinUrl('images/mascots_13.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="14">
												<img src="<?php echo $this->getSkinUrl('images/mascots_14.jpg') ?>" alt="font" class="img_sk_select_logo"  />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="15">
												<img src="<?php echo $this->getSkinUrl('images/mascots_15.jpg') ?>" alt="font" class="img_sk_select_logo"  />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="16">
												<img src="<?php echo $this->getSkinUrl('images/mascots_16.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="17">
												<img src="<?php echo $this->getSkinUrl('images/mascots_17.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="18">
												<img src="<?php echo $this->getSkinUrl('images/mascots_18.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="19">
												<img src="<?php echo $this->getSkinUrl('images/mascots_19.jpg') ?>" alt="font" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="20">
												<img src="<?php echo $this->getSkinUrl('images/mascots_20.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="21">
												<img src="<?php echo $this->getSkinUrl('images/mascots_21.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="22">
												<img src="<?php echo $this->getSkinUrl('images/mascots_22.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="23">
												<img src="<?php echo $this->getSkinUrl('images/mascots_23.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="24">
												<img src="<?php echo $this->getSkinUrl('images/mascots_24.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="25">
												<img src="<?php echo $this->getSkinUrl('images/mascots_25.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="26">
												<img src="<?php echo $this->getSkinUrl('images/mascots_26.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="27">
												<img src="<?php echo $this->getSkinUrl('images/mascots_27.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="28">
												<img src="<?php echo $this->getSkinUrl('images/mascots_28.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="29">
												<img src="<?php echo $this->getSkinUrl('images/mascots_29.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="30">
												<img src="<?php echo $this->getSkinUrl('images/mascots_30.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="31">
												<img src="<?php echo $this->getSkinUrl('images/mascots_31.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="32">
												<img src="<?php echo $this->getSkinUrl('images/mascots_32.jpg') ?>" alt="font"  class="img_sk_select_logo"  />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="33">
												<img src="<?php echo $this->getSkinUrl('images/mascots_33.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="34">
												<img src="<?php echo $this->getSkinUrl('images/mascots_34.jpg') ?>" alt="font"  class="img_sk_select_logo" />
												</a>
											</li>
											<li>
												<a href="javascript:void(0)" class="a_sk_select_logo_label" data-val="35">
												<img class="img_sk_select_logo" src="<?php echo $this->getSkinUrl('images/mascots_35.jpg') ?>" alt="font" />
												</a>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div style="    z-index: 99999;    height: 100%;    width: 100%;    background: rgba(255,255,255,0.3);    position: absolute;    top: 0;    left: 0; ">
				<div id="loader" style="margin-right:200px;margin-top:200px" ><img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>"   /></div>
			</div>
			<div style="display:none;z-index: 99999;    height: 100%;    width: 100%;    background: rgba(255,255,255,0.3);    position: absolute;    top: 0;    left: 0; ">
				<div id="webgl_error" style="text-align:center;display:none;margin-right:50px;margin-top:200px" >
					Sorry for the inconvenience<br/>
					It seems your browser does not support <br/>
					<a href="http://get.webgl.org" target="_blank" style="color:#f2700d;font-weight:600">WebGL</a>
				</div>
			</div>
			<!-- <div id="sk_canvas_overlay" style="    z-index: 9998;    height: 100%;    width: 100%;    background: rgba(255,255,255,0.3);    position: absolute;    top: 0;    left: 0; "> -->
			<!-- <div id="loader" style="margin-right:200px;margin-top:200px" ><img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>"   /></div> -->
			<!-- </div> -->
			<div class="col-md-5 text-center" id="sk_canvas_box" style="position:fixed;top:0;right:0; ">
				<a href="javascript:void(0)" id="btn_open">
				<img src="<?php echo $this->getSkinUrl('images/menu.png') ?>" alt="Open">
				</a>
				<div class="action-info "  id="sk_canvas_info">
					Click and drag to rotate, mouse wheel to zoom(3D)
				</div>
				<div id="sk_canvas_container" class="jersey sk_jersey" style="background:#464543; margin-top:20px	">
					<canvas id="sk_canvas" class="unselectable open-hand"    ></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="space sk_space">
	</div>
	<?php /*
	<script type="text/javascript">
		var oldjQuery = jQuery;
		var old$ = $;
	</script>
	<script src="https://code.jquery.com/jquery-3.0.0.js"></script>
	<script src="https://code.jquery.com/jquery-migrate-3.0.0.js"></script>
	<script  src="<?php echo $this->getSkinUrl('js/noconflict.js') ?>"></script>    
	*/ ?>
	<script src="<?php echo $this->getSkinUrl('js/jquery.min.js') ?>"></script>   
	<script src="<?php echo $this->getSkinUrl('js/sk_check.min.js') ?>"></script>   
	<script src="<?php echo $this->getSkinUrl('js/sk_sdk.min.js') ?>"></script>  
	<script src="<?php echo $this->getSkinUrl('js/sk_motion.min.js') ?>"></script>	 
	<!-- <script  src="<?php echo $this->getSkinUrl('js/sk_3d_jersey.js') ?>"></script>  -->    
	<script  src="<?php echo $this->getSkinUrl('js/sk.min.js') ?>"></script>

	<?php /*
	<script type="text/javascript">
		jQuery = oldjQuery;
		$j = jQuery;
		$ = old$;
	</script>    
	*/ ?>
	<div class="footer sk_footer">
		<div class="container">
			<!-- AddToAny BEGIN -->
			<div class="a2a_kit a2a_kit_size_32 a2a_default_style" style="position:absolute">
				<a class="a2a_dd" href="https://www.addtoany.com/share"/>
				<a class="a2a_button_facebook">
				</a><a class="a2a_button_twitter"/>
				<a class="a2a_button_google_plus"/>
			</div>
			<script async src="https://static.addtoany.com/menu/page.js"></script>
			<!-- AddToAny END -->
			<div class="footer-link">
			<a href="javascript:void(0)" class="a_sk_action" data-val="contact_me">Contact Me</a> &nbsp;&nbsp;| &nbsp;&nbsp;
			<a href="javascript:void(0)" class="a_sk_action" data-val="summary">Summary</a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	var productAddToCartForm = new VarienForm('product_addtocart_form');
	productAddToCartForm.validator.options.stopOnFirst = true;
	productAddToCartForm.submit = function(button, url) {
		var form = this.form;
		//jQuery('#sk_design_tool_box input').change();
		if (this.validator.validate()) {
			var oldUrl = form.action;

			if (url) {
			   form.action = url;
			}
			var e = null;
			try {
				_handleRosters(true);
				jQuery(form).submit();
			} catch (e) {
			}
			this.form.action = oldUrl;
			if (e) {
				throw e;
			}

			if (button && button != 'undefined') {
				button.disabled = true;
			}
		}
	}.bind(productAddToCartForm);

	productAddToCartForm.submitLight = function(button, url){
		if(this.validator) {
			var nv = Validation.methods;
			delete Validation.methods['required-entry'];
			delete Validation.methods['validate-one-required'];
			delete Validation.methods['validate-one-required-by-name'];
			// Remove custom datetime validators
			for (var methodName in Validation.methods) {
				if (methodName.match(/^validate-datetime-.*/i)) {
					delete Validation.methods[methodName];
				}
			}

			if (this.validator.validate()) {
				if (url) {
					this.form.action = url;
				}
				this.form.submit();
			}
			Object.extend(Validation.methods, nv);
		}
	}.bind(productAddToCartForm);
	
	function _handleRosters(same){
		var qtyInput = jQuery('#product_addtocart_form #qty');
		
		var rosters = jQuery('#div_sk_panel_roster table tbody tr');
		var lines = "";
		var size = '';
		var number = '';
		var name = '';
		var valsQty = 0;
		for(var g=0;g<rosters.length;++g){
			tds = rosters.eq(g).find('th,td');
			size = jQuery.trim(tds.eq(0).find('select option:selected').text());
			number = jQuery.trim(tds.eq(1).find('input').val());
			name = jQuery.trim(tds.eq(2).find('input').val());
			if(size.length > 0 || number.length > 0 || name.length > 0){
				++valsQty;
				lines = lines+valsQty+': '+size+','+number+','+name+"\n";
			}
		}
		lines = lines.replace(/\n,,/ig,'');
		lines = lines.replace(/,,/ig,'');
		jQuery('.product-custom-option.option-roster').val(jQuery.trim(lines)).change();
		
		var inputs = rosters.find('select,input').not('.handled');
		inputs.on('change', function(){
			_handleRosters();
			_handleQty();
		});
		inputs.addClass('handled');
		
		if(typeof same != 'undefined')
		{
			qtyInput.val(valsQty);
		}else{
			var qty = parseInt(qtyInput.val());
			if(valsQty >= qty){
				valsQty = (valsQty>qty?valsQty:valsQty+1);
				qtyInput.val(valsQty);
				_handleQty();
			}
		}
		
		if(parseInt(jQuery('#product_addtocart_form #qty').val())<2){
			jQuery('.product-custom-option.option-roster').val('').change();
		}
	}
	_handleRosters();
	
	
	function _handleQty(){
		var qtyInput = jQuery('#product_addtocart_form #qty');
		var qty = parseInt(qtyInput.val());
		if(qty<8){
			qty = 8;
			qtyInput.val(8).change();
			return;
		}
		var rosters = jQuery('#div_sk_panel_roster table tbody tr');
		if(qty>1){
			qtyInput.val(qty);
			jQuery('.roster-section').show();
			if(rosters.length > qty){
				rosters.slice(qty).remove();
			}else if(qty > rosters.length){
				var diff = qty - rosters.length;
				var row;
				
				for(var i=0;i<diff;++i){
					row = rosters.first().clone();
					row.find('input,select').val('');
					jQuery('#div_sk_panel_roster table tbody').append(row);
				}
			}
		}else{
			if(jQuery('#div_sk_panel_roster:visible').length>0){
				jQuery('#div_sk_panel_main').show();
			}
			jQuery('.roster-section').hide();
			jQuery('#div_sk_panel_roster').hide();
			rosters.slice(1).remove();
			qtyInput.val(1);
		}
	}
	
	function _handleSummary(){
		jQuery('.summary-details').each(function(i, e){
			var ele = jQuery(e);
			var cls = ele.attr('id').replace('summary-', 'option-');
			ele.html(jQuery('.'+cls).val());
		});
	}
	
	jQuery(document).ready(function($j){
		$j('#div_sk_panel_instruction textarea').change(function(){
			$j('.product-custom-option.option-instructions').val($j(this).val()).change();
		});
		$j('#div_sk_panel_instruction textarea').change();
		var qtyInput = $j('#product_addtocart_form #qty');
		qtyInput.change(function(){
			_handleQty();
			_handleRosters();
		});
		qtyInput.change();
		
		$j('.btn-add-line').click(function(e){
			e.preventDefault();
			
			var qty = parseInt(qtyInput.val());
			qtyInput.val(qty+1);
			qtyInput.change();
		});
		
		$j('.product-custom-option.option-shorts-mascot-stock').change(function(){
			if($j(this).val().length>0){
				jQuery('.input-file-container.option-shorts-mascot input').first().val('').change();
			}
		});
		$j('.product-custom-option.option-back-logo-stock').change(function(){
			if($j(this).val().length>0){
				jQuery('.input-file-container.option-back-logo input').first().val('').change();
			}
		});
		$j('.product-custom-option.option-front-logo-stock').change(function(){
			if($j(this).val().length>0){
				jQuery('.input-file-container.option-front-logo input').first().val('').change()
			}
		});
		
		$j('.product-custom-option').change(function(){
			_handleSummary();
		});
	});
//]]>
</script>